apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    description: |-
      Image stream for local CKAN(with extensions).

      Note:The config file is supplied for convenience in the case a new ImageStream must be created
      (eg: to hold CKAN extension images)
  labels:
    ckan.component: ckan
  name: ckan