apiVersion: v1
kind: Secret
metadata:
  annotations:
      description: |-
        Holds the install_ckan_ext.sh file
  labels:
    app: ckan
    ckan.component: ckan-ext
  name: ckan-ext-git
type: Opaque
stringData:
  install_ckan_ext.sh: |-
    # This file will be sourced inside the assemble script, given the right flags
    # Its name must be "install_ckan_ext.sh"
    # Sould contain operation on the source that was cloned with the S2I procedure

    pip install .