apiVersion: v1
kind: Secret
metadata:
  annotations:
      description: |-
        Holds the install_ckan_ext.sh file

        Note: This separate config file is similar in structure to the one inside the template.
        It is provided as a convenient way to edit and load the configuration settings herein.
  labels:
    app: ckan
    ckan.component: ckan-ext
  name: ckan-ext-git
type: Opaque
stringData:
  CKAN_EXT_DIR: "my_ckanext"
  install_ckan_ext.sh: |-
    # This file will be sourced inside the assemble script, given the right flags
    # Its name must be "install_ckan_ext.sh"
    # Should contain the install operations on the source that was cloned with the S2I procedure

    python setup.py install