apiVersion: v1
kind: Secret
metadata:
  annotations:
      description: |-
        Environment variables needed by the initialization script.
        These need to be synced with the contents of the production.ini ConfigurationMap
  labels:
    ckan.component: ckan
  name: ckan-env
type: Opaque
stringData:
# used to generate container user
  CONTAINER_USER_NAME: ckan
# env var for Docker build to install specific postgres client
  POSTGRES_TOOLS_VERSION: rh-postgresql96
  CKAN_CONFIG: /opt/app-root/config
  CKAN_TEMPLATE_CONFIG: /opt/config
