apiVersion: v1
kind: Secret
metadata:
  annotations:
      description: |-
        Environment variables needed to setup and run the ckan container.
        These need to be synced with the contents of the production.ini ConfigurationMap
        Currently reference the services/auth from resources in the same project
  labels:
    ckan.component: ckan
  name: ckan-env
type: Opaque
stringData:
# used to generate container user
  CONTAINER_USER_NAME: ckan
# env var for Docker build to install specific postgres client
  POSTGRES_TOOLS_VERSION: rh-postgresql96
# used in original Dockerfile; useful???
#    CKAN_HOME: /opt/app-root/src/ckan
# used in entrypoint and original Dockerfile; useful??
  CKAN_CONFIG: /opt/app-root/config
  CKAN_TEMPLATE_CONFIG: /opt/config
# used in original Dockerfile; useful???
#    CKAN_VENV: /opt/app-root/src
# used in docker-compose
#    CKAN_PORT: '5000'
  POSTGRES_HOST: ckan-persist-postgresql.pub-ckan.svc.cluster.local
  REDIS_HOST: ckan-persist-redis.pub-ckan.svc.cluster.local
  REDIS_PORT: '6379'
  REDIS_DB: '1'
  SOLR_HOST: ckan-solr.pub-ckan.svc.cluster.local
  SOLR_PORT: '8983'
  DATAPUSHER_HOST: ckan-datapusher.pub-ckan.svc.cluster.local
  DATAPUSHER_PORT: '8800'
#### not used: can be configured to specify HTTP Basic authentication details for all Solr requests
#    CKAN_SOLR_USER:
#    CKAN_SOLR_PASSWORD
#### also the default, internal sysadmin user name
  CKAN_SITE_ID: okd
  CKAN_SITE_URL: http://ckan.apps.oshift-pinfold.intra
  CKAN_STORAGE_PATH: /opt/app-root/storage