#!!! this Dockerfile is only used for quay.io builds mimicking S2I
FROM quay.io/dagniel/ckan-on-openshift:builder-dev

ENV DISABLE_SETUP_PY_PROCESSING ""
ENV UPGRADE_PIP_TO_LATEST "true"

ARG git_branch="ckan-2.8.3"

RUN git clone https://github.com/ckan/ckan.git /tmp/src/ && \
	cd /tmp/src && \
	git checkout ${git_branch} && \
#	cp -rf /tmp/src/* $APP_ROOT/src/ && \
	cd && \
	$STI_SCRIPTS_PATH/assemble && \
	rm -rf /tmp/src
